name: podflix

networks:
  t3_proxy:
    external: true
  podflix-network:
    name: podflix-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

services:
  podflix-db:
    image: postgres:18
    container_name: podflix-db
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - podflix-network
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/pgdata
    volumes:
      - ./deployment/volumes/podflix-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  podflix-dev:
    image: podflix-dev:latest
    container_name: podflix-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    # command: ["uv", "run", "chainlit", "run", "src/podflix/gui/audio.py", "--host", "0.0.0.0", "--port", "5000", "--headless"]
    networks:
      - t3_proxy
      - podflix-network
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
    depends_on:
      podflix-db:
        condition: service_healthy
      # langfuse-server:
      #   condition: service_healthy
      # localstack:
      #   condition: service_healthy
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    env_file:
      - .env
    environment:
      - LIBRARY_BASE_PATH=/app
      - CHAINLIT_APP_ROOT=/app/configs/chainlit
      - DATABASE_URL=postgresql://postgres:postgres@podflix-db:5432/postgres
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.podflix-rtr.entrypoints=websecure"
      - "traefik.http.routers.podflix-rtr.rule=Host(`podflix.$DOMAIN_NAME`)"
      ## HTTP Services
      - "traefik.http.routers.podflix-rtr.service=podflix-svc"
      - "traefik.http.services.podflix-svc.loadbalancer.server.port=5000"

  podflix-prod:
    image: podflix-prod:latest
    container_name: podflix-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    networks:
      - t3_proxy
      - podflix-network
    command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
    depends_on:
      podflix-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - LIBRARY_BASE_PATH=/app
      - CHAINLIT_APP_ROOT=/app/configs/chainlit
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.podflix-rtr.entrypoints=websecure"
      - "traefik.http.routers.podflix-rtr.rule=Host(`podflix.$DOMAIN_NAME`)"
      ## HTTP Services
      - "traefik.http.routers.podflix-rtr.service=podflix-svc"
      - "traefik.http.services.podflix-svc.loadbalancer.server.port=5000"
